server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone : http://discovery-server:7001/eureka/
    eureka-server-read-timeout-seconds: 30000
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000  ##暂时这样
spring:
  profiles: test
---
server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone : http://discovery-server:7001/eureka/
    eureka-server-read-timeout-seconds: 30000
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000  ##暂时这样
spring:
  profiles: pro
