server:
  port: 7777
  error:
    path: /exception/error
eureka:
  client:
    service-url:
      defaultZone : http://10.1.129.197:7001/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 10.1.129.197
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.112:3306/foreign_web?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
mybatis:
  type-aliases-package: com.hoolai.access.foreign.manager.web.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/manager/web/dao/mybatis/mapper/*Mapper.xml
oauth:
  suffix:
    open: /login,/registe
