server:
  port: 10200
  error:
    path: /exception/error
eureka:
  client:
    service-url:
      defaultZone : http://192.168.150.158:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.150.158:9092
          zk-nodes: 192.168.150.158:2181
      #bindings:
      #  input:
      #    destination: provider-order
      #  output:
      #    destination: provider-appinfo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.158:3306/foreign_appinfo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
mybatis:
  type-aliases-package: com.hoolai.access.foreign.provider.appinfo.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/provider/appinfo/dao/mybatis/mapper/*Mapper.xml
