server:
  port: ${run_port}
eureka:
  client:
    service-url:
      defaultZone : ${eureka_url}
  instance:
    prefer-ip-address: true
    ip-address: ${host_ip}
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 30
      keepAliveSeconds: 10000
      queueCapacity: 30
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 32
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 5
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/foreign_report?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    time-between-eviction-runs-millis: 300000
    num-tests-per-eviction-run: 3
    min-evictable-idle-time-millis: 3600000
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${kafka_brokers}
          zk-nodes: ${zookeeper_connect}
       # bindings:
       #   report:
       #     destination: report_stream
       #     consumer:
       #       concurrency: 1
       #       partitioned: false
       #   log:
       #     destination: log_stream
       #     consumer:
       #       concurrency: 1
       #       partitioned: false
      bindings:
        reportin:
          destination: report_stream
          group: R1
          consumer:
            concurrency: 1
            partitioned: false
        login:
          destination: log_stream
          group: L1
          consumer:
            concurrency: 1
            partitioned: false
      #instance-index: ${instanceIndex}
      #instance-count: ${serverCount}
  zipkin:
    base-url: http://zipkin-server:10400
logging:
  level: info
  config: classpath:logback-spring.xml
report:
  configs:
    bi:
      id: 200
      path: /var/bi
service.host.ip: ${host_ip}
