server:
  port: 10500
eureka:
  client:
    service-url:
      defaultZone : http://192.168.150.158:7001/eureka/
  instance:
    hostname: discovery-server
    prefer-ip-address: true
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 30
      keepAliveSeconds: 10000
      queueCapacity: 30
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.150.158:9092
          zk-nodes: 192.168.150.158:2181
        bindings:
          report:
            destination: provider-report
          log:
            destination: provider-report
service.host.ip: 192.168.150.158
