server:
  port: ${run_port}
eureka:
  client:
    service-url:
      defaultZone : ${eureka_url}
  instance:
    prefer-ip-address: true
    ip-address: ${host_ip}
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 30
      keepAliveSeconds: 10000
      queueCapacity: 30
  #datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      max-lifetime: 1800000
#      maximum-pool-size: 20
#      read-only: false
#      connection-timeout: 30000
#      idle-timeout: 600000
#      minimum-idle: 10
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://db:3306/foreign_notify?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: ${db_username}
#    password: ${db_password}
  zipkin:
    base-url: http://zipkin-server:${zipkin_port}
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  write:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://db:3306/foreign_notify?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
  read:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://db_read:3306/foreign_notify?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
mybatis:
  type-aliases-package: com.hoolai.access.foreign.provider.notify.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/provider/notify/dao/mybatis/mapper/*Mapper.xml
logging:
  level: info
  config: classpath:logback-spring.xml
service.host.ip: ${host_ip}
