server:
  port: 8301
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka/
#  instance:
#    hostname: discovery-server
#    prefer-ip-address: true
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 30
      keepAliveSeconds: 10000
      queueCapacity: 30
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.150.158:3306/foreign_notify?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
mybatis:
  type-aliases-package: com.hoolai.access.foreign.provider.notify.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/provider/notify/dao/mybatis/mapper/*Mapper.xml
