server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone : http://discovery-server:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  profiles: test
---
server:
  port: 8101
eureka:
  client:
    service-url:
      defaultZone : http://discovery-server:7001/eureka/
  instance:
    prefer-ip-address: true
spring:
  profiles: pro
