server:
  port: ${run_port}
eureka:
  client:
    service-url:
      defaultZone : ${eureka_url}
  instance:
    prefer-ip-address: true
    ip-address: ${host_ip}
spring:
  task:
    pool:
      corePoolSize: 10
      maxPoolSize: 20
      keepAliveSeconds: 300
      queueCapacity: 1000
 # datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      max-lifetime: 1800000
#      maximum-pool-size: 32
#      read-only: false
#      connection-timeout: 30000
#      idle-timeout: 600000
#      minimum-idle: 5
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://db:3306/foreign_report?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: ${db_username}
#    password: ${db_password}
#    time-between-eviction-runs-millis: 300000
#    num-tests-per-eviction-run: 3
#    min-evictable-idle-time-millis: 3600000
#  cloud:
#   stream:
#     kafka:
#       binder:
#         brokers: ${kafka_brokers}
#         zk-nodes: ${zookeeper_connect}
#         auto-add-partitions: true
#         auto-create-topics: true
#         min-partition-count: 1
#     bindings:
#       log:
#         destination: gamecollection
#         producer:
#           partitionCount: 1
  zipkin:
    base-url: http://zipkin-server:${zipkin_port}
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  write:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://db:3306/foreign_report?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
  read:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://db_read:3306/foreign_report?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
logging:
  level: info
  config: classpath:logback-spring.xml
report:
  configs:
    bi:
      id: 300
      path: /var/bi
service.host.ip: ${host_ip}
