server:
  port: 8401
  error:
    path: /exception/error
eureka:
  client:
    service-url:
      defaultZone : http://192.168.1.197:7001/eureka/
  instance:
#    hostname: discovery-server
    prefer-ip-address: true
    ip-address: 192.168.1.197
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.150.158:9092
          zk-nodes: 192.168.150.158:2181
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.20.112:3306/foreign_finance?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
  zipkin:
    base-url: http://192.168.1.197:10400
mybatis:
  type-aliases-package: com.hoolai.access.foreign.provider.finance.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/provider/finance/dao/mybatis/mapper/*Mapper.xml