server:
  port: ${run_port}
  tomcat:
    accept-count: 1000
    max-threads: 2000
    min-spare-threads: 1000
security:
  user:
    password: barsecret
    name: bar
  oauth2:
    client:
      client-id: yvz5o319oolklggq
      client-secret: 7g8trcvehjp4bi52
      authorized-grant-types: refresh_token,password
      scope: openid
eureka:
  client:
    service-url:
      defaultZone : ${eureka_url}
  instance:
    prefer-ip-address: true
    ip-address: ${host_ip}
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 1800000
      maximum-pool-size: 20
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      minimum-idle: 10
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://db:3306/hl_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
mybatis:
  type-aliases-package: com.hoolai.access.foreign.core.oauth.dao.mybatis.vo
  mapper-locations: classpath:com/hoolai/access/foreign/core/oauth/dao/mybatis/mapper/*Mapper.xml
