server:
  port: 10400
eureka:
  client:
    service-url:
      defaultZone : http://10.1.129.197:7001/eureka/
  instance:
    hostname: discovery-server
    prefer-ip-address: true
spring:
  datasource:
    url: jdbc:mysql://db:3306/foreign_zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    continue-on-error: true
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql