server:
  port: 10400
eureka:
  client:
    service-url:
      defaultZone : http://10.1.129.197:7001/eureka/
  instance:
    hostname: discovery-server
    prefer-ip-address: true
spring:
  sleuth:
    enabled: false
datasource:
  type: com.zaxxer.hikari.HikariDataSource
  write:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://10.1.1.253:3306/foreign_zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
  read:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://10.1.1.253:3306/foreign_zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: hoolai
    max-lifetime: 1800000
    maximum-pool-size: 32
    read-only: false
    connection-timeout: 30000
    idle-timeout: 600000
    minimum-idle: 20
zipkin:
  storage:
    type: mysql