server:
  port: ${run_port}
  error:
    path: /exception/error
eureka:
  client:
    service-url:
      defaultZone : ${eureka_url}
  instance:
    prefer-ip-address: true
    ip-address: ${host_ip}
logging:
  level: info
  config: classpath:logback-spring.xml
spring:
  datasource:
    url: jdbc:mysql://db:3306/foreign_zipkin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${db_username}
    password: ${db_password}
    continue-on-error: true
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    enabled: false
zipkin:
  storage:
    type: mysql